import { dir } from 'i18next';
import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';

import { WrappedToast } from '@/components/Elements/Toast';
import { Header } from '@/components/Layouts/Header';
import { ReduxProvider } from '@/stores/ReduxProvider';

import './globals.css';
import { languages } from '../i18n/settings';

const inter = Noto_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700']
});

export async function generateStaticParams() {
  return languages.map(lang => ({ lang }));
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children,
  params: { lang }
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return (
    <html lang={lang} dir={dir(lang)}>
      <body className={inter.className}>
        <WrappedToast />
        <ReduxProvider>
          <Header />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
